### ISSUE TITLE
Cities of Sigmar tracker

### ISSUE THREAD

**Issue by cartag** [BSData/warhammer-age-of-sigmar#1059]
- [x] Battle Traits
- [x] Hammerhall Battle Traits, Command Traits, Relics, Lores
- [x] The Living City Battle Traits, Command Traits, Relics, Lores
- [x] Greywater Fastness Battle Traits, Command Traits, Relics, Lores
- [x] The Phoenicium Battle Traits, Command Traits, Relics, Lores
- [x] Anvilgard Battle Traits, Command Traits, Relics, Lores, Curses
- [x] Hallowheart Battle Traits, Command Traits, Relics, Lores
- [x] Tempest's Eye Battle Traits, Command Traits, Relics, Lores
- [x] Battalions
- [x] Warscrolls

- [x] Freeguilds
- [x] Devoted of Sigmar
- [x] Collegiate Arcane
- [x] Darkling Coven
- [x] Dispossessed
- [x] Ironweld Arsenal
- [x] Phoenix Temple
- [x] Order Serpentis
- [x] Shadowblades
- [x] Scourge Privateers
- [x] Wanderers

- [x] Battleline logic test

**Comment by cartag** [comment]
- [ ] Points
