### ISSUE TITLE
Morathi Tracker

### ISSUE THREAD

**Issue by cartag** [BSData/warhammer-age-of-sigmar#1533]
- [x] Daughters of Khaine
- [x] Idoneth Deepkin 
- [x] Cities of Sigmar
- [x] Stormcast Eternals
- [x] Slaves to Darkness
