### ISSUE TITLE
Add Harbingers to catalogues

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/warhammer-age-of-sigmar#170]
Harbingers should be added to the catalogue for the Allegiance with which they are associated.

They can be Generals even when they are Allies (you will need to create a model-specific General SE which doesn't hide when the model is in an Ally force) but can only select Allegiance abilities for their own Allegiance.

- [x] Darkoath Warqueen (Slaves to Darkness)
- [x] Lord-Ordinator (Stormcast Eternal)
- [x] Knight of Shrouds (Nighthaunt)
- [x] Fungoid Cave-shaman (Moonclan)

**Comment by rweyrauch** [comment]
Lord-Ordinator added in pull request #180.

**Comment by tekton** [comment]
The shaman is in there, but something went wrong in his General flagging...going to work on that this week
