### ISSUE TITLE
Add Shadespire units to catalogues

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/warhammer-age-of-sigmar#171]
- [x] Garrek's Reavers (Khorne Bloodbound)
- [x] Spiteclaw's Swarm (Skaven Verminus)
- [x] Sepulchral Guard (Deathrattle)
- [x] Ironskull's Boyz (Ironjawz)
- [x] Steelheart's Champions (Stormcast Eternal)
- [x] The Farstriders (Stormcast Eternal)
- [x] Magore’s Fiends (Khorne Bloodbound)
- [x] The Chosen Axes (Fyreslayers)

**Comment by rweyrauch** [comment]
Steelheart's Champions added in pull request #180.

**Comment by OftKilted** [comment]
Updated to include The Farstriders and Magore’s Fiends (and Riptooth) 
https://www.games-workshop.com/resources/PDF/Downloads//aos-warscroll-magores-fiends-en.pdf
https://www.games-workshop.com/resources/PDF/Downloads//aos-warscroll-the-farstriders-en.pdf

**Comment by rweyrauch** [comment]
Magore's Fiends added to Khorne catalog.
