### ISSUE TITLE
Request: Support for the Firestorm Campaign Allegiance Abilities

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#172]
## THIS IS NOT REQUIRED TO BE COMPLETED FOR THE INITIAL RELEASE.

The Firestorm Campaign has additional Allegiance Abilities that can be used when selecting a Grand Alliance army that meets specific criteria.

Death:
- [x] THE WRAITH FLEET

Destruction:
- [ ] STONEKLAW'S GUTSTOMPAS

Order:
- [ ] HAMMERHAL
- [ ] ANVILGUARD
- [ ] TEMPEST'S EYE
- [ ] HALLOWHEART
- [ ] THE LIVING CITY
- [ ] GREYWATER FASTNESS
- [ ] THE PHOENICIUM

Chaos:
- [ ] FIST OF THE EVERCHOSEN

**Comment by cartag** [comment]
Closing with release of Cities of Sigmar
