### ISSUE TITLE
AoS 3 Progress Tracker - Points and Updates for Battalions and Enhancements

### ISSUE THREAD

**Issue by cartag** [BSData/warhammer-age-of-sigmar#1871]
Needing QA
- [x] Beasts of Chaos
- [x] Khorne
- [x] Nurgle
- [x] Skaven
- [x] Slaanesh
- [x] Slaves to Darkness
- [x] Tzeentch
- [x] Flesh Eater Courts
- [x] Soulblight Gravelords
- [x] Nighthaunt
- [x] Sons of Behemat
- [x] Sylvaneth
- [x] Cities of Sigmar
- [x] Daughters of Khaine
- [x] Fyreslayers
- [x] Idoneth Deepkin
- [x] Kharadron Overlords
- [x] Lumineth Realm-Lords
- [x] Seraphon
- [x] Ossiarch Bonereapers
- [x] Orruk Warclans
- [x] Gloomspite Gitz
- [x] Ogor Mawtribes
- [x] Stormcast Eternals

**Comment by rweyrauch** [comment]
I believe all catalogs have been updated for AoS3.

Need a QA pass before release.
