### ISSUE TITLE
Death v2.0 Release Ready Status

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#191]
Current Catalog Status:
All profiles have been entered and are being split out into the following catalogs:

- Legions of Nagash
- Flesh Eater Courts
- Death Warscroll Compendium Battletome

**Legions of Nagash** (Legions of Night catalog)
- [ ] Grand Host of Nagash
- [ ] Legion of Sacrament
- [ ] Legion of Blood
- [ ] Legion of Night

**GHB 2017** (Legions of Night catalog)
- [ ] Deadwalkers
- [ ] Deathlords
- [ ] Deathmages
- [ ] Deathrattle
- [ ] (Deathrattle) Shadespire: The Sepulchral Guard
- [ ] Nighthaunt
- [ ] (Nighthaunt) Malign Portents: Harbinger 
- [ ] Soulblight

**GHB 2017** (Flesh Eater Courts catalog)
- [ ] Flesh-eater Courts 

**Compendium:** (Death catalog)
- [ ] Tomb Kings
- [ ] Vampire Counts

**Comment by OftKilted** [comment]
Tomb Kings and Vampire Counts have been given their own catalogs
