### ISSUE TITLE
Chaos Catalogue - Allegiance: Nurgle

### ISSUE THREAD

**Issue by FreylisUK** [BSData/warhammer-age-of-sigmar#215]
Chaos - Nurgle.cat is missing profiles and validation and SSEs. Update 'Chaos - Nurgle.cat' to include items listed below:

- [x] Units
- [x] Profiles
- [x] Allies
- [x] Keywords/Categories
- [x] Battle Traits: Artefacts
- [x] Battle Traits: Spell Lore
- [x] Battle Traits: Command Traits
- [x] Battalion: Profiles
- [x] FAQ Updates

**Comment by FreylisUK** [comment]
This should be in a release-ready state now.
