### ISSUE TITLE
Order: Battalions - Normalize battalion descriptions.

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#231]
Use the 'Battalion Organisation' profile type instead of 'Rule' for battalion organisation descriptions.   Refer to "Death - Flesh-eater Courts.cat" as an example.

- [x]  Order.cat
- [x]  Order - Bretonnia.cat
- [x]  Order - Darkling Covens.cat
- [x]  Order - Daughters of Khaine.cat
- [x]  Order - Dispossessed.cat
- [x]  Order - Dwarfs.cat
- [x]  Order - Free Peoples.cat
- [x]  Order - Fyreslayers.cat
- [x]  Order - Kharadron Overlords.cat
- [x]  Order - Seraphon.cat
- [x]  Order - Stormcast Eternals.cat
- [x]  Order - Sylvaneth.cat
- [x]  Order - Wanderers.cat
- [x]  Order - Wood Elves.cat

**Comment by OftKilted** [comment]
Battalion Validation does work if you use the model in the 'Flesh Eater Courts' (it just isn't documented yet)
