### ISSUE TITLE
Chaos v2.0 Release Ready Status

### ISSUE THREAD

**Issue by FreylisUK** [BSData/warhammer-age-of-sigmar#255]
**Core Catalogues**
- [x] Brayherds (Brayherds.cat)
- [x] Chaos Gargants (Chaos Gargants.cat)
- [x] Daemons of Chaos (Daemons of Chaos.cat)
- [x] Everchosen (Everchosen.cat)
- [x] Khorne (Khorne.cat)
- [x] Monsters of Chaos (Monsters of Chaos.cat)
- [x] Nurgle (Nurgle.cat)
- [x] Skaven (Skaven.cat)
- [x] Slaanesh (Slaanesh.cat)
- [x] Slaves to Darkness (Slaves to Darkness.cat)
- [x] Thunderscorn (Thunderscorn.cat)
- [x] Tzeentch (Tzeentch.cat)
- [x] Warherds (Warherds.cat)

**Forge World Catalogues**
- [x] Exalted Greater Daemons (Khorne.cat, Nurgle.cat, Slaanesh.cat and Tzeentch.cat)
- [x] Monstrous Arcanum (Monsters of Chaos.cat)
- [x] Tamurkhan's Horde (Nurgle.cat and Slaves to Darkness.cat)
- [x] Legion of Azgorh (Legion of Azgorh.cat)
- [x] Shar'Tor the Executioner (Legion of Azgorh.cat)
- [x] Skaven Warlord on Brood Horror (Skaven.cat)
- [x] Wolf Rats (Skaven.cat)
- [x] Warpgnaw Verminlord (Skaven.cat)

**FAQ Updates**
- [x] GENERAL’S HANDBOOK 2017 26/02/2018
- [x] CHAOS FAQs and Errata, v1.4 29/01/2018
   - [x] GRAND ALLIANCE: CHAOS 
   - [x] BLADES OF KHORNE
   - [x] DISCIPLES OF TZEENTCH
   - [x] MAGGOTKIN OF NURGLE
- [x] WARHAMMER AGE OF SIGMAR: BLIGHTWAR 9/2017

**Comment by FreylisUK** [comment]
The Legion of Azgorh catalogue is currently in progress.

**Comment by OftKilted** [comment]
Tzeentch cat completed.

**Comment by rweyrauch** [comment]
Bug fixes for Brayherds and Khorne are in a pull-request.

**Comment by rweyrauch** [comment]
I suggest the Everchosen Warscroll battalions at least be present in a catalog with the correct points.

**Comment by OftKilted** [comment]
The cross cat validation might work better if we had an actual “Allegiance:(Allegiance Name)” Category. 

Not just an “Allegiance name” which can often overlap with a keyword.

That would allow doing a “Hide if Not instance of ‘Allegiance:(Allegiance name)” in Roster.

And one could setup the SSE for Allegiances to have the category selected referenced. (Much like how we have “General” currently. (Probably need to do actual testing to see if it does proper validation (like the Everchosen warbands)

**Comment by rweyrauch** [comment]
PR #262 addresses issues in Chaos - Monsters of Chaos catalog.

**Comment by OftKilted** [comment]
Skaven Completed. GHB and CHAOS FAQs applied to SKAVEN.cat

**Comment by OftKilted** [comment]
Chaos.cat split out into remaining catalogs per #296
