### ISSUE TITLE
Chaos Catalog - Skaven Release State

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#268]
Chaos - Skaven.cat is missing profiles and validation and SSEs

Update 'Chaos - Skaven.cat' to include items listed below:
- [x] Eshin
- [x] Moulder
- [x] Moulder (forgeworld)
- [x] Pestilens
- [x] Pestilens (battalions)
- [x] Verminous
- [x] Verminous (forgeworld)
- [x] Masterclan
- [x] Skryre
- [x] Skryre Battalions & Enginecovens

Validate 'Chaos - skaven.cat' listed below:
- [x] Unit Profiles
- [x] Keywords/Categories
- [x] Battle Traits: Artefacts
- [x] Battle Traits: Spell Lore
- [x] Battle Traits: Command Traits
- [x] Battalion: Profiles
- [x] Root Selection Entries (Leader/Battleline/Other/etc.)
- [x] Allies 
- [x] Battalion: Validation
- [x] FAQ Updates

**Forgeworld Units**
- [x] Forgeworld Unit Profiles
- [x] Forgeworld Keywords & Categories
- [x] Forgeworld Root Selection Entries (Leader/Battleline/Other/etc.)

**Comment by OftKilted** [comment]
Resolved Forgeworld Items with #277
