### ISSUE TITLE
Destruction v2.0 Release Ready Status

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#270]
Destruction (GHB 2017) Pitched Battle Factions

**Core Allegiance Catalogs:**
- [x] BeastClaw Raiders
- [x] Bonesplitterz
- [x] Ironjawz

**Destruction Allegiance**
- [x] Aleguzzler Gargants
- [x] Firebellies
- [x] Gitmob Grots
- [x] Greenskinz
- [x] Gutbusters
- [x] Maneaters
- [x] Moonclan Grots
- [x] Spiderfang Grots
- [x] Troggoths

**Grots**
- [x] Different entries for different point costs - share everything else

**Bonesplitterz**
- [x] Remove units that aren't in the Battletome when Destruction is selected

**Ironjawz**
- [x] Remove units that aren't in the Battletome when Destruction is selected

**BeastClaw Raiders**
- [x] Remove units that aren't in the Battletome when Destruction is selected
- [x] Battle lines for Frost Savers and Icefall Yhetees

**Across board cleanup**
- [x] Damage table clean up
- [x] Break out result tables from dice rolls
- [x] Aretfacts standardized
- [x] Command Traits standardized
- [x] Weapon selection clean up
- [x] FAQ Updates: https://whc-cdn.games-workshop.com/wp-content/uploads/2017/11/age_of_sigmar_destruction_en-1.pdf

**Comment by tekton** [comment]
Most of these are done, but I'll do the sanity checks tomorrow night

**Comment by tekton** [comment]
Closing this so we can open new issues for each CAT
