### ISSUE TITLE
Order v2.0 Release Ready Status

### ISSUE THREAD

**Issue by FreylisUK** [BSData/warhammer-age-of-sigmar#272]
**Core Catalogues**
- [x] Collegiate Arcane (Order.cat)
- [x] Darkling Covens (Darkling Covens.cat)
- [x] Daughters of Khaine (Daughters of Khaine.cat)
- [x] Devoted of Sigmar (Order.cat)
- [x] Dispossessed (Dispossessed.cat)
- [x] Eldritch Council (Order.cat)
- [x] Free Peoples (Free Peoples.cat)
- [x] Fyreslayers (Fyreslayers.cat)
- [x] Idoneth Deepkin (Idoneth Deepkin.cat)
- [x] Ironweld Arsenal (Order.cat)
- [x] Kharadron Overlords (Kharadron Overlords.cat)
- [x] Lion Rangers (Order.cat)
- [x] Order Draconis (Order.cat)
- [x] Order Serpentis (Order.cat)
- [x] Phoenix Temple (Order.cat)
- [x] Scourge Privateers (Order.cat)
- [x] Seraphon (Seraphon.cat)
- [x] Shadowblades (Order.cat)
- [x] Stormcast Eternals (Stormcast Eternals.cat)
- [x] Sylvaneth (Sylvaneth.cat)
- [x] Swifthawk Agents (Order.cat)
- [x] Wanderers (Wanderers.cat)

**Forge World Catalogues**
- [x] Dread Saurian (Seraphon.cat)

**FAQ Updates**
- [x] GENERAL’S HANDBOOK 2017 26/02/2018
- [x] GRAND ALLIANCE: ORDER 19/03/2018
- [x] WARHAMMER AGE OF SIGMAR: BLIGHTWAR 9/2017
