### ISSUE TITLE
ORDER - Split out "Grand Alliance: Order" factions from order.cat into sub-Grand Alliance catalogs

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#298]
The Following Factions have individual factions, but no Allegiance outside of GA:Order.

To make it easier for list creation using allies the factions below will be split out of the current order.cat units into their individual "sub faction" lists:

- [ ] Aelf (Order.cat)
- [ ] Collegiate Arcane (Order.cat)
- [ ] Devoted of Sigmar (Order.cat)
- [ ] Eldritch Council (Order.cat)
- [ ] Ironweld Arsenal (Order.cat)
- [ ] Lion Rangers (Order.cat)
- [ ] Order Draconis (Order.cat)
- [ ] Order Serpentis (Order.cat)
- [ ] Phoenix Temple (Order.cat)
- [ ] Scourge Privateers (Order.cat)
- [ ] Shadowblades (Order.cat)
- [ ] Swifthawk Agents (Order.cat)

**Comment by OftKilted** [comment]
Updated Collegiate Arcane:
Celestial Hurricanum incorrectly showing as 'Leader' when Celestial Mage not added
Luminark of Hysh incorrectly showing as 'Leader' when White Mage not added
Luminark and Hurricanum missing Artefacts
Luminark and Hurricanum unable to be selected as general

**Comment by OftKilted** [comment]
Splitting Eldritch Council

**Comment by OftKilted** [comment]
Corrected issues:
Archmage on Dragon unable to choose between arcane tome and sorcerous blade
Archmage on Dragon and Archmage unable to 'not select' Arcane Talisman.
Hornblower and Standard bearer not available as 'selectable' options.
