### ISSUE TITLE
Remove 'Hiding' for Grand Alliance Battle Traits in Skaven/Tzeentch/Death Catalogs

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#320]
Issue:
When a 'Sub Faction' of a grand alliance is taken the Grand Alliance Battle Traits (Artefacts/Command Traits) are hidden by default. Remove the 'enforcement' of hiding the Grand Alliance Battle Traits for the v2.0 release in the following catalogs.

- [x] Chaos - Tzeentch.cat
- [x] Chaos - Skaven.cat
- [x] Death - Legions of Nagash.cat
- [x] Death - Flesh Eater Courts.cat

**Comment by OftKilted** [comment]
Resolved with #324
