### ISSUE TITLE
Apply catalog Guidelines to Order catalogs.

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#354]
Add SEs for all weapons.
Add SEs for optional abilities (banners, drummers, etc.)

Catalogs:
- [x] 'Order - Aelf.cat'
- [x] 'Order - Bretonnia.cat'
- [x] 'Order - Collegiate Arcane.cat'
- [x] 'Order - Darkling Covens.cat'
- [x] 'Order - Daughters of Khaine.cat'
- [x] 'Order - Devoted of Sigmar.cat'
- [x] 'Order - Dispossessed.cat'
- [x] 'Order - Dwarfs.cat'
- [x] 'Order - Eldritch Council.cat'
- [x] 'Order - Free Peoples.cat'
- [x] 'Order - Fyreslayers.cat'
- [x] 'Order - Idoneth Deepkin.cat'
- [x] 'Order - Ironweld Arsenal.cat'
- [x] 'Order - Kharadron Overlords.cat'
- [x] 'Order - Lion Rangers.cat'
- [x] 'Order - Monstrous Arcanum.cat'
- [x] 'Order - Order Draconis.cat'
- [x] 'Order - Order Serpentis.cat'
- [x] 'Order - Phoenix Temple.cat'
- [x] 'Order - Scourge Privateers.cat'
- [x] 'Order - Seraphon.cat'
- [x] 'Order - Shadowblades.cat'
- [x] 'Order - Stormcast Eternals.cat'
- [x] 'Order - Switfhawk Agents.cat'
- [x] 'Order - Sylvaneth.cat'
- [x] 'Order - Wanderers.cat'
- [x] 'Order - Wood Elves.cat'

**Comment by OftKilted** [comment]
Before we go too far in the Command Trait Location move, let’s make sure that we’re all in accord.
After working with that as a solution, I’m not sure that having them as a sub-item is the best implementation for folks on mobile for us to “Move Command Traits to General SSE.”

**Comment by OftKilted** [comment]
Picking up Aelf
