### ISSUE TITLE
Leftover html text formatting tokens.

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#373]
The following catalogs have leftover html tokens.   These tokens are no longer used by BS and clutter up the output text.   Remove and reformat as needed.

- [x] Chaos - Khorne.cat
- [x] Death - Legions of Nagash.cat
- [x] Death - Tomb Kings.cat
- [x] Destruction - Beastclaw Raiders.cat
- [x] Destruction - Greenskinz.cat
- [x] Destruction - Ironjawz.cat
- [x] Destruction - Moonclan Grots.cat
- [x] Order - Kharadron Overlords.cat
- [x] Order - Seraphon.cat
- [x] Order - Stormcast Eternals.cat
