### ISSUE TITLE
AoS v2.0 Death - GHB 2018 Points Update

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#473]
Update Points with 2018 changes

**Legions of Nagash** (Legions of Night catalog)
- [x] Grand Host of Nagash
- [x] Legion of Sacrament
- [x] Legion of Blood
- [x] Legion of Night

**Nighthaunt Battletome (Soul Wars)** (Nighthaunt catalog)
- [x] Nighthaunt
- [x] (Nighthaunt) Malign Portents: Harbinger

**GHB 2018** (Legions of Night catalog)
~~Deadwalkers~~ (Pending: Pulled from GHB?)
~~Deathlords~~ (Pending: Pulled from GHB?)
~~Deathmages~~ (Pending: Pulled from GHB?)
~~Deathrattle~~ (Pending: Pulled from GHB?)
- [x] (Deathrattle) Shadespire: The Sepulchral Guard
- [x] Nighthaunt
- [x] (Nighthaunt) Malign Portents: Harbinger 
- [x] Soulblight

**GHB 2018** (Flesh Eater Courts catalog)
- [x] Flesh-eater Courts 

**Compendium:**
- [x] ~~Tomb Kings (Tomb King Catalog)~~ (No Updates Expected)
- [x] ~~Vampire Counts (Vampire Counts Catalog)~~ (No Updates Expected)

**Forgeworld**
- [x] Mourngul
