### ISSUE TITLE
AoS v2.0 Chaos - GHB 2018 Points Update

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#474]
Update Chaos with new Points

**Core Catalogues**
~~Beastmen (Beastmen.cat)~~ Pending Compendium Points Update
- [x] Brayherds (Brayherds.cat)
- [x] Chaos Gargants (Chaos Gargants.cat)
- [x] Daemons of Chaos (Daemons of Chaos.cat)
- [x] Everchosen (Everchosen.cat)
- [x] Khorne (Khorne.cat)
- [x] - Blades of Khorne
- [x] -- Blades of Khorne Battalions
- [x] - Non-Blades of Khorne
- [x] Monsters of Chaos (Monsters of Chaos.cat)
- [x] Nurgle (Nurgle.cat)
- [x] Skaven (Skaven.cat)
- [x] Slaanesh (Slaanesh.cat)
- [x] Slaves to Darkness (Slaves to Darkness.cat)
- [x] Thunderscorn (Thunderscorn.cat)
- [x] Tzeentch (Tzeentch.cat)
- [x] - Disciples of Tzeentch
- [x] - Non-Disciples of Tzeentch
- [x] Warherds (Warherds.cat)

**Forge World Catalogues**
- [x] Exalted Greater Daemons
- [x] - Khorne.cat
- [x] - Nurgle.cat, 
- [x] - Slaanesh.cat and 
- [x] - Tzeentch.cat
- [x] Mazrall the Butcher (Khorne.cat)
- [x] Monstrous Arcanum (Monsters of Chaos.cat, Khorne.cat, Tzeentch.cat and Slaves to Darkness.cat)
- [x] Tamurkhan's Horde (Nurgle.cat)
- [x] Legion of Azgorh (Legion of Azgorh.cat)
- [x] Shar'Tor the Executioner (Legion of Azgorh.cat)
- [x] Skaven Warlord on Brood Horror (Skaven.cat)
- [x] Brood Horror (Skaven.cat)
- [x] Wolf Rats (Skaven.cat)
- [x] Warpgnaw Verminlord (Skaven.cat)
