### ISSUE TITLE
AoS v2.0 Order - GHB 2018 Points Update

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#476]
Update to new 2018 points when points are released

**Catalogues**
- [x] Aelf (Aelf.cat)
- [x] Bretonnia (Bretonnia.cat)
- [x] Collegiate Arcane (Collegiate Arcane.cat)
- [x] Darkling Covens (Darkling Covens.cat)
- [x] Daughters of Khaine (Daughters of Khaine.cat)
- [x] Devoted of Sigmar (Devoted of Sigmar.cat)
- [x] Dispossessed (Dispossessed.cat)
- [x] Dwarfs (Dwarfs.cat)
- [x] Eldritch Council (Eldritch Council.cat)
- [x] Free Peoples (Free Peoples.cat)
- [x] Fyreslayers (Fyreslayers.cat)
- [x] Idoneth Deepkin (Idoneth Deepkin.cat)
- [x] Ironweld Arsenal (Ironweld Arsenal.cat)
- [x] Kharadron Overlords (Kharadron Overlords.cat)
- [x] Lion Rangers (Lion Rangers.cat)
- [x] Order Draconis (Order Draconis.cat)
- [x] Order Serpentis (Order Serpentis.cat)
- [x] Phoenix Temple (Phoenix Temple.cat)
- [x] Scourge Privateers (Scourge Privateers.cat)
- [x] Seraphon (Seraphon.cat)
- [x] Shadowblades (Shadowblades.cat)
- [x] Stormcast Eternals (Stormcast Eternals.cat)
- [x] Swifthawk Agents (Swifthawk Agents.cat)
- [x] Sylvaneth (Sylvaneth.cat)
- [x] Wanderers (Wanderers.cat)
- [x] Wood Elves (Wood Elves.cat)

**Forge World Catalogues**
- [x] Dread Saurian (Seraphon.cat)
- [x] Monstrous Arcanum (Monstrous Arcanum.cat)
