### ISSUE TITLE
Request: Endless Spells

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#481]
Endless Spells will be available to all armies in the new edition. Add “endless spells force type”? (Kind of like scenery ... but not?)

Selection Entries
- [x] Aethervoid Pendulum 
- [x] Balewind Vortex 
- [x] Chronomantic Cogs 
- [x] Emerald Lifeswarm 
- [x] Geminids of Uhl-Gyish﻿ 
- [x] Malevolent Maelstrom﻿ 
- [x] Prismatic Palisade﻿ 
- [x] Purple Sun of Shyish﻿ 
- [x] Quicksilver Swords﻿ 
- [x] Ravenak's Gnashing Jaws﻿ 
- [x] Soulsnare Shackles﻿ 
- [x] Suffocating﻿﻿ Gravetide﻿﻿ 
- [x] The B﻿urning Head﻿﻿﻿﻿ 
- [x] Umbral Sp﻿ellporta﻿l﻿﻿﻿

Profiles
- [x] Aethervoid Pendulum https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Aethervoid_Pendulum.pdf
- [x] Balewind Vortex https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Balewind_Vortex.pdf
- [x] Chronomantic Cogs https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Chronomantic_Cogs.pdf
- [x] Emerald Lifeswarm https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Emerald_lifeswarm.pdf
- [x] Geminids of Uhl-Gyish﻿ https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Geminids_of_Uhl_Gysh.pdf
- [x] Malevolent Maelstrom﻿ https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Malevolent_Maelstrom.pdf
- [x] Prismatic Palisade﻿ https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Prismatic_palisade.pdf
- [x] Purple Sun of Shyish﻿ https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Purple_sun_of_shyish.pdf
- [x] Quicksilver Swords﻿ https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Quicksilver_swords.pdf
- [x] Ravenak's Gnashing Jaws﻿ https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Ravenaks_gnashing_jaws.pdf
- [x] Soulsnare Shackles﻿ https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Soulsnare_Shackles.pdf
- [x] Suffocating﻿﻿ Gravetide﻿﻿ https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_Suffocating_gravetide.pdf
- [x] The B﻿urning Head﻿﻿﻿﻿ https://www.games-workshop.com/resources/PDF/Downloads//ENG_Malign_Sorcery_The_Burning_Head.pdf
- [x] Umbral Sp﻿ellporta﻿l﻿﻿﻿ ﻿https://www.games-workshop.com﻿/resources/PDF/Downloads//ENG_Malign_Sorcery_Umbral_Spellportal.pdf

**Comment by OftKilted** [comment]
Endless Spells:
1. Purple Sun of Shyish - Single model endless spell with a casting value of 8, if successfully cast set up this model within 6’ of the caster. When this model is cast the player who cast it can immediately make a move with it. It has a move of 9’ and can fly if the battle is in Shyish the move is 12 instead. “End Given Form” After this model has moved any units that have models it passed across, and each unit within 1’ at the end of its move must roll a dice for each model in the unit. For each 6+ one model in the unit is slain unless they have 6 or more wounds in which case they suffer 2D6 mortal wounds. Subtract 1 from the Bravery of all units while they are within 6’ of this model.
2. Ravenak's Gnashing Jaws -“Ravening Hunger” After this model has moved, each unit that has any models it passed across, and each other unit within 1’ at the end of its move, suffers D3 mortal wound. In addition, subtract 1 from their bravery until the end of the battle round.
3. Prismatic Palisade
4. Aethervoid Pendulum - “Scything Blade” After this model has moved, each unit that has any models it passed across, and each other unit that is within 1” of it at the end of its move, suffers D6 mortal wounds.
5. Suffocating Gravetide - “Pulled to the Grave” After this model has moved, each unit that has any models it passed across suffers D3 mortal wounds. In addition, subtract 1 from their bravery until the end of the battle round.
6. Umbral Spellportal - A single endless spell that consists of 2 models with a casting value of 5, if successfully cast set up the first Spellportal within 12 of the caster and the second within 18 of the first. If within the Realm of Ulgu the second can be set up anywhere on the board instead of within 18 of the first. “Arcane Passage” If a wizard casts a spell while they are within 1” of a Spellportal model, the range and visibility of the spell can be measured from the other Umbral Spellportal model. If an Endless Spell finishes a move within 6” of an Umbral Spellportal model, remove it from the battlefield and set it up again anywhere within 6” of the other Umbral Spellportal model.
7. Malevolent Maeostrom
8. Quicksilver Swords
9. The Burning Head
10. Geminids of UHL-GYSH
11. Chronomatic Cogs - “Mechanisms of Time” In their controlling players hero phase, a single Wizard within 9’ of this model may choose to do one of the following things. Speed Up Time: Add 2’ to the Move characteristics of all units on the battlefield. In addition, add 2 to charge rolls for all units on the battlefield. Slow Down Time: The wizard manipulating the cogs can cast an additional spell in this hero phase. In addition, re-roll failed save rolls for that wizard.
12. Soulsnare Shackles
13. Emerald Lifeswarm
(14) Balewind Vortex

**Comment by rweyrauch** [comment]
The endless spells are purchased at roster creation time using the standard roster points.   As are command points.

This would mean that endless spells be included in the GST and managed/selected like other units/models.
