### ISSUE TITLE
Add SGE Link to the Local SSEG for 'ArtefactsProfiles for the 'Realm Artefacts of Power' local SSEG 

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#491]
The "Realm Artefacts of Power" is an SSEG GST item that has links to the SSEG's for all of the Realm specific Artefacts of power. The specific realm artefacts show/hide depending on whether an 'Realm of Origin' has been selected for the Roster. (If no Realm of Origin is selected i.e. left at the default of '*NONE*' then the Artefacts are hidden.)

GA Order Armies
- [x] Aelf.cat
- [x] Bretonnia.cat
- [x] Collegiate Arcane.cat
- [x] Darkling Covens.cat
- [x] Daughters of Khaine.cat
- [x] Devoted of Sigmar.cat
- [x] Dispossessed.cat
- [x] Dwarfs.cat
- [x] Eldritch Council.cat
- [x] Empire.cat
- [x] Free Peoples.cat
- [x] Fyreslayers.cat
- [x] High Elves.cat
- [x] Idoneth Deepkin.cat
- [x] Ironweld Arsenal.cat
- [x] Kharadron Overlords.cat
- [x] Lion Rangers.cat
- [x] Monstrous Arcanum.cat
- [x] Order Draconis.cat
- [x] Order Serpentis.cat
- [x] Phoenix Temple.cat
- [x] Scourge Privateers.cat
- [x] Seraphon.cat
- [x] Shadowblades.cat
- [x] Stormcast Eternals.cat
- [x] Switfhawk Agents.cat
- [x] Sylvaneth.cat
- [x] Wanderers.cat
- [x] Wood Elves.cat

- [x] GA Chaos Armies

- [x] GA Destruction Armies

- [x] GA Death Armies
